import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { expect, userEvent } from 'storybook/test';
import { CemElementRuntime } from './cem-elements.js';

const meta: Meta = { title: 'CEM Elements/Form Control', tags: ['test'] };
export default meta;
type Story = StoryObj;
interface FormHost extends HTMLElement {
    value: string;
    form: HTMLFormElement | null;
    validity: ValidityState;
    checkValidity(): boolean;
    setCustomValidity(message: string): void;
    formStateRestoreCallback(value: string, mode: 'restore' | 'autocomplete'): void;
}

export const Lifecycle: Story = {
    render: () => document.createElement('section'),
    play: async ({ canvasElement }) => {
        const runtime = new CemElementRuntime({ declarationTag: 'form-control-declaration' });
        runtime.install(window);
        const declaration = document.createElement('form-control-declaration');
        declaration.setAttribute('tag', 'story-form-control');
        declaration.setAttribute('capability', 'form-control');
        const template = document.createElement('template');
        template.setAttribute('type', 'text/cem-ml');
        template.textContent = '{input @part=control @form="" @aria-label=Account @type=email @value={datadom.slices.value} @disabled={if datadom.slices.formDisabled { true } else { null }} @required={if seq:count(datadom.attributes.required) > 0 { true } else { null }} @readonly={if seq:count(datadom.attributes.readonly) > 0 { true } else { null }} @slice=value @slice-event=input @slice-value="$target.value"}';
        declaration.append(template);
        canvasElement.append(declaration);
        runtime.registerDeclaration(declaration);
        await runtime.whenDeclarationSettled(declaration);
        expect(runtime.diagnosticsFor(declaration)).toEqual([]);
        const form = document.createElement('form');
        form.innerHTML = '<fieldset><story-form-control name="account" value="initial@example.com" required></story-form-control></fieldset><button type="reset">Reset</button>';
        canvasElement.append(form);
        const host = form.querySelector('story-form-control') as FormHost;
        const settle = () => runtime.whenRenderSettled(host);
        await settle();
        const input = (host.querySelector('input') as HTMLInputElement);
        expect(host.form).toBe(form);
        expect(Array.from(form.elements)).toContain(host);
        expect(input.hasAttribute('name')).toBe(false);
        expect(new FormData(form).getAll('account')).toEqual(['initial@example.com']);
        await userEvent.clear(input);
        await userEvent.type(input, 'edited@example.com');
        await settle();
        expect(host.value).toBe('edited@example.com');
        expect(new FormData(form).getAll('account')).toEqual(['edited@example.com']);
        await userEvent.click((form.querySelector('button') as HTMLButtonElement));
        await settle();
        expect(input.value).toBe('initial@example.com');
        expect(host.value).toBe('initial@example.com');
        host.setAttribute('busy', '');
        await settle();
        expect(input.value).toBe('initial@example.com');

        host.value = '';
        await settle();
        expect(host.validity.valueMissing).toBe(true);
        expect(host.checkValidity()).toBe(false);
        host.value = 'invalid-email';
        await settle();
        expect(host.validity.typeMismatch).toBe(true);
        host.value = 'valid@example.com';
        await settle();
        expect(host.checkValidity()).toBe(true);
        host.setCustomValidity('Application error');
        expect(host.validity.customError).toBe(true);
        host.setCustomValidity('');
        expect(host.checkValidity()).toBe(true);
        host.setAttribute('readonly', '');
        host.value = '';
        await settle();
        expect(host.checkValidity()).toBe(true);
        host.removeAttribute('readonly');

        (form.querySelector('fieldset') as HTMLFieldSetElement).disabled = true;
        await settle();
        expect(input.disabled).toBe(true);
        expect(new FormData(form).getAll('account')).toEqual([]);
        (form.querySelector('fieldset') as HTMLFieldSetElement).disabled = false;
        await settle();
        expect(input.disabled).toBe(false);
        host.formStateRestoreCallback('restored@example.com', 'restore');
        await settle();
        expect(input.value).toBe('restored@example.com');
        expect(new FormData(form).getAll('account')).toEqual(['restored@example.com']);
        form.reset();
        await settle();
        expect(input.value).toBe('initial@example.com');
        expect(host.querySelector('input')).toBe(input);

        host.setAttribute('value', 'new-default@example.com');
        await settle();
        expect(input.value).toBe('new-default@example.com');
        host.value = 'dirty@example.com';
        await settle();
        const cancelReset = (event: Event) => event.preventDefault();
        form.addEventListener('reset', cancelReset);
        form.reset();
        await settle();
        expect(input.value).toBe('dirty@example.com');
        form.removeEventListener('reset', cancelReset);
        form.reset();
        await settle();
        expect(input.value).toBe('new-default@example.com');
        const external = document.createElement('form');
        external.id = 'external-form-control-owner';
        canvasElement.append(external);
        host.setAttribute('form', external.id);
        await settle();
        expect(input.form).toBeNull();
        expect(host.form).toBe(external);
        expect(new FormData(form).getAll('account')).toEqual([]);
        expect(new FormData(external).getAll('account')).toEqual(['new-default@example.com']);
        host.removeAttribute('name');
        await settle();
        expect([...new FormData(external)]).toEqual([]);
        host.setAttribute('name', 'renamed');
        await settle();
        expect(new FormData(external).getAll('renamed')).toEqual(['new-default@example.com']);
        if (import.meta.env.MODE !== 'test') return;
        const { userEvent: nativeUser } = await import('vitest/browser');
        const submitted: Array<HTMLElement | null> = [];
        external.addEventListener('submit', event => {
            event.preventDefault();
            submitted.push((event as SubmitEvent).submitter);
        });
        input.focus();
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(1);
        const blocker = document.createElement('input');
        external.append(blocker);
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(1);
        const submit = document.createElement('button');
        submit.type = 'submit';
        external.append(submit);
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(2);
        expect(submitted[1]).toBe(submit);
        submit.disabled = true;
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(2);
        submit.disabled = false;
        const cancelKey = (event: KeyboardEvent) => event.preventDefault();
        canvasElement.addEventListener('keydown', cancelKey);
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(2);
        canvasElement.removeEventListener('keydown', cancelKey);
        const cancelClick = (event: Event) => event.preventDefault();
        submit.addEventListener('click', cancelClick);
        await nativeUser.keyboard('{Enter}');
        expect(submitted).toHaveLength(2);
        submit.removeEventListener('click', cancelClick);
        expect(runtime.diagnosticsFor(host)).toEqual([]);
    },
};
