//! Generate the implemented URL registry reference; run from the workspace root.
use cem_ql::stdlib::{url, ModuleRegistry};

fn main() {
    println!("# Implemented URL functions\n");
    println!(
        "Generated by `cargo run -p cem-ql --example url_reference` from the native registry.\n"
    );
    println!("Default alias: `url`; explicit import: `import \"cem:stdlib/url\" as u`.\n");
    println!("See the [value contract](../../../../../docs/cem-ql-url-contract.md) for exact argument and result shapes.\n");
    println!("| Function | Arity | Tier | Implementation |");
    println!("| --- | --- | --- | --- |");
    for function in ModuleRegistry::with_all_known()
        .functions
        .iter()
        .filter(|f| f.module == url::MODULE_URI)
    {
        let arity = if function.min_arity == function.max_arity {
            function.min_arity.to_string()
        } else {
            format!("{}–{}", function.min_arity, function.max_arity)
        };
        println!(
            "| `url:{}` | {} | {:?} | {:?} |",
            function.name, arity, function.tier, function.implementation
        );
    }
    println!("\nThese entries describe implemented native query calls. Remaining URL conformance gaps are tracked separately in the repository checklist.");
    println!("\n## Executable examples\n");
    println!("Generated from the shared [query/result matrix](../../../../cem_ql/fixtures/url/query-matrix.json), exercised by native, Node WASM and browser tests. The CLI verifies all 30 rows using explicit expression/module identities and preserves nonfatal setter warnings. JSON below is the explicitly requested typed query-result projection.\n");
    let cases: Vec<serde_json::Value> =
        serde_json::from_str(include_str!("../fixtures/url/query-matrix.json"))
            .expect("URL matrix");
    for id in [
        "href-relative",
        "mapping",
        "import-alias",
        "sort-utf16",
        "setter-warning",
        "invalid-base",
    ] {
        let case = cases
            .iter()
            .find(|case| case["id"] == id)
            .expect("documented example");
        println!(
            "### {id}\n\n```cem-ql\n{}\n```\n",
            case["query"].as_str().expect("query")
        );
        println!("```json\n{}\n```\n", serde_json::to_string_pretty(&serde_json::json!({
            "items": case["items"], "diagnosticCodes": case["diagnosticCodes"], "error": case["error"]
        })).expect("control result"));
    }
    println!("The matrix also covers empty results, duplicate entries, optional values and upstream failures.");
}
