//! Generate the implemented URL registry reference; run from the workspace root.
use cem_ql::stdlib::{url, ModuleRegistry};

fn main() {
    println!("# Implemented URL functions\n");
    println!(
        "Generated by `cargo run -p cem-ql --example url_reference` from the native registry.\n"
    );
    println!("Default alias: `url`; explicit import: `import \"cem:stdlib/url\" as u`.\n");
    println!("See the [value contract](../../../../../docs/cem-ql-url-contract.md) for exact argument and result shapes.\n");
    println!("| Function | Arity | Tier | Implementation |");
    println!("| --- | --- | --- | --- |");
    for function in ModuleRegistry::with_all_known()
        .functions
        .iter()
        .filter(|f| f.module == url::MODULE_URI)
    {
        let arity = if function.min_arity == function.max_arity {
            function.min_arity.to_string()
        } else {
            format!("{}–{}", function.min_arity, function.max_arity)
        };
        println!(
            "| `url:{}` | {} | {:?} | {:?} |",
            function.name, arity, function.tier, function.implementation
        );
    }
    println!("\nThese entries describe implemented native query calls. Browser/CLI/SSR parity and remaining URL conformance gaps are tracked separately in the repository checklist.");
}
