/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__name_token = 1,
  aux_sym_directive_token1 = 2,
  sym__directive_head = 3,
  sym__directive_body = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_DOLLAR = 7,
  anon_sym_AT = 8,
  anon_sym_EQ = 9,
  sym_bare_value = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_string_token1 = 12,
  anon_sym_DQUOTE2 = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_quoted_string_token2 = 15,
  anon_sym_SQUOTE2 = 16,
  aux_sym_cem_ql_span_token1 = 17,
  anon_sym_PIPE = 18,
  anon_sym_u25b7 = 19,
  sym_qname = 20,
  sym_line_comment = 21,
  sym_block_comment = 22,
  sym_rich_content = 23,
  sym_text = 24,
  sym_document = 25,
  sym_directive = 26,
  sym__item = 27,
  sym_node = 28,
  sym_anonymous_scope = 29,
  sym_expression_node = 30,
  sym_attribute = 31,
  sym__attribute_value = 32,
  sym_quoted_string = 33,
  sym_cem_ql_span = 34,
  sym_expression_body = 35,
  sym_content_boundary = 36,
  aux_sym_document_repeat1 = 37,
  aux_sym_document_repeat2 = 38,
  aux_sym_node_repeat1 = 39,
  aux_sym_quoted_string_repeat1 = 40,
  aux_sym_quoted_string_repeat2 = 41,
  aux_sym_cem_ql_span_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__name_token] = "_name_token",
  [aux_sym_directive_token1] = "directive_token1",
  [sym__directive_head] = "_directive_head",
  [sym__directive_body] = "_directive_body",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = "=",
  [sym_bare_value] = "bare_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_string_token2] = "quoted_string_token2",
  [anon_sym_SQUOTE2] = "'",
  [aux_sym_cem_ql_span_token1] = "cem_ql_span_token1",
  [anon_sym_PIPE] = "|",
  [anon_sym_u25b7] = "\u25b7",
  [sym_qname] = "qname",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_rich_content] = "rich_content",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_directive] = "directive",
  [sym__item] = "_item",
  [sym_node] = "node",
  [sym_anonymous_scope] = "anonymous_scope",
  [sym_expression_node] = "expression_node",
  [sym_attribute] = "attribute",
  [sym__attribute_value] = "_attribute_value",
  [sym_quoted_string] = "quoted_string",
  [sym_cem_ql_span] = "cem_ql_span",
  [sym_expression_body] = "expression_body",
  [sym_content_boundary] = "content_boundary",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_node_repeat1] = "node_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_quoted_string_repeat2] = "quoted_string_repeat2",
  [aux_sym_cem_ql_span_repeat1] = "cem_ql_span_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__name_token] = sym__name_token,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [sym__directive_head] = sym__directive_head,
  [sym__directive_body] = sym__directive_body,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_bare_value] = sym_bare_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_string_token2] = aux_sym_quoted_string_token2,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [aux_sym_cem_ql_span_token1] = aux_sym_cem_ql_span_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_u25b7] = anon_sym_u25b7,
  [sym_qname] = sym_qname,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_rich_content] = sym_rich_content,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_directive] = sym_directive,
  [sym__item] = sym__item,
  [sym_node] = sym_node,
  [sym_anonymous_scope] = sym_anonymous_scope,
  [sym_expression_node] = sym_expression_node,
  [sym_attribute] = sym_attribute,
  [sym__attribute_value] = sym__attribute_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_cem_ql_span] = sym_cem_ql_span,
  [sym_expression_body] = sym_expression_body,
  [sym_content_boundary] = sym_content_boundary,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_node_repeat1] = aux_sym_node_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_quoted_string_repeat2] = aux_sym_quoted_string_repeat2,
  [aux_sym_cem_ql_span_repeat1] = aux_sym_cem_ql_span_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__name_token] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__directive_head] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_body] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cem_ql_span_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u25b7] = {
    .visible = true,
    .named = false,
  },
  [sym_qname] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_rich_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_node] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_cem_ql_span] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_body] = {
    .visible = true,
    .named = true,
  },
  [sym_content_boundary] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cem_ql_span_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_body, 2},
  [3] =
    {field_body, 3},
  [4] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 15,
  [21] = 11,
  [22] = 22,
  [23] = 14,
  [24] = 24,
  [25] = 16,
  [26] = 12,
  [27] = 17,
  [28] = 10,
  [29] = 19,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 49,
  [50] = 43,
  [51] = 47,
  [52] = 52,
  [53] = 44,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 55,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 61,
  [64] = 56,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 60,
  [69] = 54,
  [70] = 66,
  [71] = 62,
  [72] = 58,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 37,
  [78] = 38,
  [79] = 79,
  [80] = 80,
  [81] = 57,
  [82] = 82,
  [83] = 82,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 107,
        '$', 91,
        '\'', 115,
        '/', 94,
        '=', 93,
        '@', 92,
        '`', 14,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34);
      if (('-' <= lookahead && lookahead <= ':')) ADVANCE(98);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(107);
      if (lookahead == '/') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(100);
      if (lookahead == '\'') ADVANCE(108);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(115);
      if (lookahead == '/') ADVANCE(112);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0) ADVANCE(114);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(130);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(131);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '/', 4,
        '=', 93,
        '@', 92,
        '`', 14,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
        '\t', 137,
        '\n', 137,
        '\r', 137,
        ' ', 137,
      );
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '/', 4,
        '@', 92,
        '`', 14,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
        '\t', 138,
        '\n', 138,
        '\r', 138,
        ' ', 138,
      );
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '}') ADVANCE(90);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(161);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(116);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '|') ADVANCE(124);
      if (lookahead == 0x25b7) ADVANCE(126);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(122);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(116);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '}') ADVANCE(90);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 12:
      if (lookahead == '`') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == '`') ADVANCE(132);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == '`') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(13);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 31:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 32:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\n', 39,
        '\r', 133,
        '/', 4,
        '@', 21,
        '`', 14,
        '{', 88,
        '\t', 133,
        ' ', 133,
      );
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 33:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\n', 39,
        '\r', 133,
        '/', 41,
        '@', 66,
        '`', 52,
        '{', 89,
        '}', 87,
        '\t', 47,
        ' ', 47,
      );
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 34:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 100,
        '$', 91,
        '\'', 108,
        '/', 94,
        '=', 93,
        '@', 92,
        '`', 14,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34);
      if (('-' <= lookahead && lookahead <= ':')) ADVANCE(98);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 35:
      if (eof) ADVANCE(38);
      if (lookahead == '$') ADVANCE(91);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '@') ADVANCE(92);
      if (lookahead == '}') ADVANCE(90);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '@') ADVANCE(21);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(133);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(133);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__directive_head);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '/') ADVANCE(87);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(136);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(43);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(136);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(43);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == '@') ADVANCE(67);
      if (lookahead == '`') ADVANCE(53);
      if (lookahead == '{') ADVANCE(89);
      if (lookahead == '}') ADVANCE(87);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(87);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(86);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(146);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(57);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(51);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(48);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(49);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(146);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(54);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '`') ADVANCE(55);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(146);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'a') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'a') ADVANCE(86);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'a') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'c') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'c') ADVANCE(86);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'c') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'c') ADVANCE(75);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'd') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(80);
      if (lookahead == 's') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'd') ADVANCE(69);
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead == 's') ADVANCE(65);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == 'o') ADVANCE(63);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'f') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'f') ADVANCE(61);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'h') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'h') ADVANCE(71);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'l') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'l') ADVANCE(83);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'm') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 's') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 's') ADVANCE(86);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 't') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 't') ADVANCE(86);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'u') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == 'u') ADVANCE(77);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__directive_body);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(99);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == ':') ADVANCE(97);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(98);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ':') ADVANCE(98);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_bare_value);
      if (('-' <= lookahead && lookahead <= ':')) ADVANCE(98);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_bare_value);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_bare_value);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(130);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '*') ADVANCE(101);
      if (lookahead == '/') ADVANCE(106);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '*') ADVANCE(101);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '"') ADVANCE(130);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(106);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '*') ADVANCE(102);
      if (lookahead == '/') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '/') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '*') ADVANCE(109);
      if (lookahead == '/') ADVANCE(114);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '*') ADVANCE(109);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\'') ADVANCE(130);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(114);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '*') ADVANCE(110);
      if (lookahead == '/') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(114);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '/') ADVANCE(112);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '*') ADVANCE(118);
      if (lookahead == '/') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '*') ADVANCE(117);
      if (lookahead == '/') ADVANCE(122);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '*') ADVANCE(117);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '/') ADVANCE(116);
      if (lookahead == '|') ADVANCE(124);
      if (lookahead == 0x25b7) ADVANCE(126);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(122);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '/') ADVANCE(116);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(122);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(130);
      if (lookahead != 0) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_cem_ql_span_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_u25b7);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_u25b7);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_qname);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_qname);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_rich_content);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\n', 39,
        '\r', 133,
        '/', 134,
        '@', 151,
        '`', 144,
        '{', 88,
        '\t', 133,
        ' ', 133,
      );
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(136);
      if (lookahead == '/') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(135);
      if (lookahead == '/') ADVANCE(131);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(136);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(135);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '/', 134,
        '=', 93,
        '@', 92,
        '`', 144,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
        '\t', 137,
        '\n', 137,
        '\r', 137,
        ' ', 137,
      );
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '/', 134,
        '@', 92,
        '`', 144,
        '{', 88,
        '|', 123,
        '}', 90,
        0x25b7, 125,
        '\t', 138,
        '\n', 138,
        '\r', 138,
        ' ', 138,
      );
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '/', 134,
        '@', 161,
        '`', 144,
        '{', 88,
        '}', 90,
        '\t', 139,
        '\n', 139,
        '\r', 139,
        ' ', 139,
      );
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(134);
      if (lookahead == '@') ADVANCE(161);
      if (lookahead == '`') ADVANCE(144);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(134);
      if (lookahead == '@') ADVANCE(151);
      if (lookahead == '`') ADVANCE(144);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(132);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(142);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(145);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(152);
      if (lookahead == 'n') ADVANCE(158);
      if (lookahead == 's') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(154);
      if (lookahead == 'o') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'f') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'h') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(161);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 36},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 36},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 37},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 33},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 36},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 36},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 35},
  [45] = {.lex_state = 36},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 35},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 37},
  [56] = {.lex_state = 37},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 37},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 37},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 37},
  [71] = {.lex_state = 37},
  [72] = {.lex_state = 37},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 11},
  [78] = {.lex_state = 11},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 11},
  [82] = {.lex_state = 35},
  [83] = {.lex_state = 35},
  [84] = {.lex_state = 35},
  [85] = {.lex_state = 35},
  [86] = {.lex_state = 35},
  [87] = {.lex_state = 35},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__name_token] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_bare_value] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_u25b7] = ACTIONS(1),
    [sym_qname] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [sym_rich_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(84),
    [sym_directive] = STATE(8),
    [sym__item] = STATE(24),
    [sym_node] = STATE(24),
    [sym_anonymous_scope] = STATE(24),
    [sym_expression_node] = STATE(24),
    [aux_sym_document_repeat1] = STATE(8),
    [aux_sym_document_repeat2] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym__directive_head] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rich_content] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    STATE(9), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(23), 2,
      sym_rich_content,
      sym_text,
    STATE(18), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(27), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [36] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(27), 2,
      sym_rich_content,
      sym_text,
    STATE(5), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(14), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [72] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(31), 2,
      sym_rich_content,
      sym_text,
    STATE(18), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(17), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [108] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(35), 2,
      sym_rich_content,
      sym_text,
    STATE(18), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(16), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [144] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(39), 2,
      sym_rich_content,
      sym_text,
    STATE(7), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(23), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [180] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_content_boundary,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    ACTIONS(43), 2,
      sym_rich_content,
      sym_text,
    STATE(18), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    STATE(25), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [216] = 7,
    ACTIONS(9), 1,
      sym__directive_head,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 2,
      sym_rich_content,
      sym_text,
    STATE(39), 2,
      sym_directive,
      aux_sym_document_repeat1,
    STATE(22), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [245] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(51), 2,
      sym_rich_content,
      sym_text,
    STATE(28), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [267] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [289] = 5,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 2,
      sym_rich_content,
      sym_text,
    STATE(11), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [311] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(35), 2,
      sym_rich_content,
      sym_text,
    STATE(16), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [333] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(67), 2,
      sym_rich_content,
      sym_text,
    STATE(10), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [355] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [377] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(71), 2,
      sym_rich_content,
      sym_text,
    STATE(19), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [399] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [421] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [443] = 4,
    ACTIONS(75), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_attribute,
      aux_sym_node_repeat1,
    ACTIONS(73), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [463] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [485] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(82), 2,
      sym_rich_content,
      sym_text,
    STATE(29), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [507] = 5,
    ACTIONS(84), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [529] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(94), 2,
      sym_rich_content,
      sym_text,
    STATE(11), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [551] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [573] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(94), 2,
      sym_rich_content,
      sym_text,
    STATE(11), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [595] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [617] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(43), 2,
      sym_rich_content,
      sym_text,
    STATE(25), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [639] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [661] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [683] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_rich_content,
      sym_text,
    STATE(21), 5,
      sym__item,
      sym_node,
      sym_anonymous_scope,
      sym_expression_node,
      aux_sym_document_repeat2,
  [705] = 3,
    ACTIONS(102), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [722] = 7,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      aux_sym_cem_ql_span_token1,
    STATE(50), 1,
      sym_content_boundary,
    STATE(87), 1,
      sym_expression_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    STATE(52), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [747] = 7,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      aux_sym_cem_ql_span_token1,
    STATE(43), 1,
      sym_content_boundary,
    STATE(85), 1,
      sym_expression_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 2,
      anon_sym_PIPE,
      anon_sym_u25b7,
    STATE(52), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [772] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      sym_bare_value,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_SQUOTE,
    STATE(35), 3,
      sym__attribute_value,
      sym_quoted_string,
      sym_cem_ql_span,
  [796] = 5,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      aux_sym_directive_token1,
    ACTIONS(124), 1,
      sym__directive_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 4,
      sym__directive_head,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [816] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [830] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(128), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [844] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [858] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(132), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [872] = 5,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 1,
      sym__directive_head,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(39), 2,
      sym_directive,
      aux_sym_document_repeat1,
    ACTIONS(139), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [892] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_PIPE,
      anon_sym_u25b7,
      sym_rich_content,
      sym_text,
  [906] = 4,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 1,
      aux_sym_directive_token1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(147), 4,
      sym__directive_head,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [923] = 3,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(151), 4,
      sym__directive_head,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [937] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      aux_sym_cem_ql_span_token1,
    STATE(83), 1,
      sym_expression_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [955] = 5,
    ACTIONS(153), 1,
      anon_sym_DOLLAR,
    ACTIONS(155), 1,
      anon_sym_AT,
    ACTIONS(157), 1,
      sym_qname,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_attribute,
      aux_sym_node_repeat1,
  [973] = 3,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(161), 4,
      sym__directive_head,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [987] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(47), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1005] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    ACTIONS(169), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(49), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1023] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1041] = 5,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(49), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1059] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      aux_sym_cem_ql_span_token1,
    STATE(82), 1,
      sym_expression_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1077] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(49), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1095] = 5,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      aux_sym_cem_ql_span_token1,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(49), 2,
      sym_cem_ql_span,
      aux_sym_cem_ql_span_repeat1,
  [1113] = 5,
    ACTIONS(155), 1,
      anon_sym_AT,
    ACTIONS(187), 1,
      anon_sym_DOLLAR,
    ACTIONS(189), 1,
      sym_qname,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_attribute,
      aux_sym_node_repeat1,
  [1131] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1142] = 3,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(195), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1155] = 3,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(199), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1168] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1179] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(203), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1190] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(195), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1201] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(205), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1212] = 3,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1225] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(211), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1236] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1247] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(199), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1258] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(213), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1269] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(215), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_rich_content,
      sym_text,
  [1280] = 3,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(213), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1293] = 3,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(205), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1306] = 3,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1319] = 3,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(215), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1332] = 3,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(211), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1345] = 3,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(203), 3,
      anon_sym_LBRACE,
      sym_rich_content,
      sym_text,
  [1358] = 4,
    ACTIONS(229), 1,
      aux_sym_quoted_string_token2,
    ACTIONS(231), 1,
      anon_sym_SQUOTE2,
    STATE(76), 1,
      aux_sym_quoted_string_repeat2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1372] = 4,
    ACTIONS(233), 1,
      aux_sym_quoted_string_token2,
    ACTIONS(236), 1,
      anon_sym_SQUOTE2,
    STATE(74), 1,
      aux_sym_quoted_string_repeat2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1386] = 4,
    ACTIONS(238), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(240), 1,
      anon_sym_DQUOTE2,
    STATE(80), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1400] = 4,
    ACTIONS(240), 1,
      anon_sym_SQUOTE2,
    ACTIONS(242), 1,
      aux_sym_quoted_string_token2,
    STATE(74), 1,
      aux_sym_quoted_string_repeat2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1414] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_cem_ql_span_token1,
  [1424] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(132), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_cem_ql_span_token1,
  [1434] = 4,
    ACTIONS(231), 1,
      anon_sym_DQUOTE2,
    ACTIONS(244), 1,
      aux_sym_quoted_string_token1,
    STATE(75), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1448] = 4,
    ACTIONS(246), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(249), 1,
      anon_sym_DQUOTE2,
    STATE(80), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1462] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 2,
      anon_sym_LBRACE,
      aux_sym_cem_ql_span_token1,
  [1471] = 2,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
  [1479] = 2,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
  [1487] = 2,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
  [1495] = 2,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
  [1503] = 2,
    ACTIONS(259), 1,
      sym_qname,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
  [1511] = 2,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 245,
  [SMALL_STATE(10)] = 267,
  [SMALL_STATE(11)] = 289,
  [SMALL_STATE(12)] = 311,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 355,
  [SMALL_STATE(15)] = 377,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 421,
  [SMALL_STATE(18)] = 443,
  [SMALL_STATE(19)] = 463,
  [SMALL_STATE(20)] = 485,
  [SMALL_STATE(21)] = 507,
  [SMALL_STATE(22)] = 529,
  [SMALL_STATE(23)] = 551,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 595,
  [SMALL_STATE(26)] = 617,
  [SMALL_STATE(27)] = 639,
  [SMALL_STATE(28)] = 661,
  [SMALL_STATE(29)] = 683,
  [SMALL_STATE(30)] = 705,
  [SMALL_STATE(31)] = 722,
  [SMALL_STATE(32)] = 747,
  [SMALL_STATE(33)] = 772,
  [SMALL_STATE(34)] = 796,
  [SMALL_STATE(35)] = 816,
  [SMALL_STATE(36)] = 830,
  [SMALL_STATE(37)] = 844,
  [SMALL_STATE(38)] = 858,
  [SMALL_STATE(39)] = 872,
  [SMALL_STATE(40)] = 892,
  [SMALL_STATE(41)] = 906,
  [SMALL_STATE(42)] = 923,
  [SMALL_STATE(43)] = 937,
  [SMALL_STATE(44)] = 955,
  [SMALL_STATE(45)] = 973,
  [SMALL_STATE(46)] = 987,
  [SMALL_STATE(47)] = 1005,
  [SMALL_STATE(48)] = 1023,
  [SMALL_STATE(49)] = 1041,
  [SMALL_STATE(50)] = 1059,
  [SMALL_STATE(51)] = 1077,
  [SMALL_STATE(52)] = 1095,
  [SMALL_STATE(53)] = 1113,
  [SMALL_STATE(54)] = 1131,
  [SMALL_STATE(55)] = 1142,
  [SMALL_STATE(56)] = 1155,
  [SMALL_STATE(57)] = 1168,
  [SMALL_STATE(58)] = 1179,
  [SMALL_STATE(59)] = 1190,
  [SMALL_STATE(60)] = 1201,
  [SMALL_STATE(61)] = 1212,
  [SMALL_STATE(62)] = 1225,
  [SMALL_STATE(63)] = 1236,
  [SMALL_STATE(64)] = 1247,
  [SMALL_STATE(65)] = 1258,
  [SMALL_STATE(66)] = 1269,
  [SMALL_STATE(67)] = 1280,
  [SMALL_STATE(68)] = 1293,
  [SMALL_STATE(69)] = 1306,
  [SMALL_STATE(70)] = 1319,
  [SMALL_STATE(71)] = 1332,
  [SMALL_STATE(72)] = 1345,
  [SMALL_STATE(73)] = 1358,
  [SMALL_STATE(74)] = 1372,
  [SMALL_STATE(75)] = 1386,
  [SMALL_STATE(76)] = 1400,
  [SMALL_STATE(77)] = 1414,
  [SMALL_STATE(78)] = 1424,
  [SMALL_STATE(79)] = 1434,
  [SMALL_STATE(80)] = 1448,
  [SMALL_STATE(81)] = 1462,
  [SMALL_STATE(82)] = 1471,
  [SMALL_STATE(83)] = 1479,
  [SMALL_STATE(84)] = 1487,
  [SMALL_STATE(85)] = 1495,
  [SMALL_STATE(86)] = 1503,
  [SMALL_STATE(87)] = 1511,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(44),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_node_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(53),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 4, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cem_ql_span, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cem_ql_span, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cem_ql_span_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cem_ql_span_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cem_ql_span_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_body, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 4, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_scope, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_scope, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 5, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 5, 0, 2),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_boundary, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 3, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_node, 4, 0, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_node, 5, 0, 4),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_node, 5, 0, 4),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_scope, 4, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_scope, 5, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 6, 0, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_scope, 5, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_node, 4, 0, 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4, 0, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 6, 0, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_scope, 4, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat2, 2, 0, 0), SHIFT_REPEAT(74),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat2, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cem(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__name_token,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
